import { Alert, Avatar, BackTop, Breadcrumb, Card, Carousel, DatePicker, Divider, Empty, List, Modal, Radio, Slider, Spin, Table, Tag, Timeline, Tooltip, Upload, AutoComplete, Button, Checkbox, Col, ConfigProvider, Dropdown, Form, FormModel, Icon, Input, InputNumber, Layout, Menu, message, Pagination, Row, Select, Steps, Tabs, Popconfirm, Space, Switch } from "ant-design-vue";
import Vue from "vue";

Vue.component(ConfigProvider.name, ConfigProvider);
Vue.component(Alert.name, Alert);
Vue.component(Pagination.name, Pagination);
Vue.component(Icon.name, Icon);
Vue.component(Layout.name, Layout);
Vue.component(Layout.Header.name, Layout.Header);
Vue.component(Layout.Content.name, Layout.Content);
Vue.component(Layout.Footer.name, Layout.Footer);
Vue.component(Layout.Sider.name, Layout.Sider);
Vue.component(Button.name, Button);
Vue.component(Select.name, Select);
Vue.component(Select.Option.name, Select.Option);
Vue.component(Select.OptGroup.name, Select.OptGroup);
Vue.component(Checkbox.name, Checkbox);
Vue.component(Checkbox.Group.name, Checkbox.Group);
Vue.component(Input.name, Input);
Vue.component(Row.name, Row);
Vue.component(Col.name, Col);
Vue.component(Tabs.name, Tabs);
Vue.component(Steps.name, Steps);
Vue.component(Steps.Step.name, Steps.Step);
Vue.component(Form.name, Form);
Vue.component(Form.Item.name, Form.Item);
Vue.component(Input.Password.name, Input.Password);
Vue.component(Input.Search.name, Input.Search);
Vue.component(FormModel.name, FormModel);
Vue.component(FormModel.Item.name, FormModel.Item);
Vue.component(Breadcrumb.name, Breadcrumb);
Vue.component(Breadcrumb.Item.name, Breadcrumb.Item);
Vue.component(Avatar.name, Avatar);
Vue.component(Input.TextArea.name, Input.TextArea);
Vue.component(Tabs.name, Tabs);
Vue.component(Tabs.TabPane.name, Tabs.TabPane);
Vue.component(FormModel.name, FormModel);
Vue.component(FormModel.Item.name, FormModel.Item);
Vue.component(Radio.name, Radio);
Vue.component(Radio.Group.name, Radio.Group);
Vue.component(Radio.Button.name, Radio.Button);
Vue.component(Slider.name, Slider);
Vue.component(Upload.name, Upload);
Vue.component(Empty.name, Empty);
Vue.component(Spin.name, Spin);
Vue.component(Table.name, Table);
Vue.component(Table.Column.name, Table.Column);
Vue.component(Divider.name, Divider);
Vue.component(DatePicker.name, DatePicker);
Vue.component(DatePicker.RangePicker.name, DatePicker.RangePicker);
Vue.component(Timeline.name, Timeline);
Vue.component(Timeline.Item.name, Timeline.Item);
Vue.component(InputNumber.name, InputNumber);
Vue.component(Card.name, Card);
Vue.component(Tag.name, Tag);
Vue.component(List.name, List);
Vue.component(Tooltip.name, Tooltip);
Vue.component(Dropdown.name, Dropdown);
// Vue.component(Menu.name, Menu);

Vue.component(Menu.Item.name, Menu.Item);
Vue.component(Carousel.name, Carousel);
Vue.component(BackTop.name, BackTop);
Vue.component(AutoComplete.name, AutoComplete);
Vue.component(Modal.confirm.name, Modal.confirm);
Vue.component(Popconfirm.name, Popconfirm);
Vue.component(Switch.name, Switch);
Vue.component(Space.name, Space);
Vue.use(Modal);
Vue.use(Menu);
Vue.prototype.$confirm = Modal.confirm;
Vue.prototype.$warning = Modal.warning;
Vue.prototype.$message = message;
